spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT%2B8&autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
server:
  port: 9001
  servlet:
    context-path: /system
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.vedio.system: trace
