spring:
  application:
    name: gateway
  #路由转发配置
  cloud:
    gateway:
      routes:
        - id: system                          #路由的ID，没有固定规则但要求唯一，简易配合服务名
            uri: http://localhost:9001        #匹配后提供服务的路由地址
            predicates:
              - Path=/system/**               #断言，路径相匹配的进行路由
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/